version: "3.9"
services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_DB: "mobiles"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.13.0-rc.4
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - "5672:5672"
      - "15672:15672"
